---
apiVersion: v1
kind: Service
metadata:
  name: manhellosrv
  labels:
    app: manhello
spec:
  selector:
    app: manhello
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080