apiVersion: apps/v1
kind: Deployment
metadata:
  name: manhello
spec:
  selector:
      matchLabels:
        app: manhello
  replicas: 1
  template:
    metadata:
      labels:
        app: manhello
    spec:
      containers:
        - name: manhello
          image: manhellosrv:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080